/*
This file has been autogenerated by build_DTWax.sh for the data in ../data_files/192_128.txt
If you have a new data file, building using build_DTWax.sh <your data file> is recommended.
*/

#ifndef DATA_DIMS_HPP
#define DATA_DIMS_HPP

#define REF_LEN 192
#define QUERY_LEN 128
#define NUM_READS 1
#define REF_BATCH (REF_LEN / REF_TILE_SIZE)

#endif // DATA_DIMS_HPP
